name: basic_engine
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  shared_preferences: ^0.5.4+5
  dio: ^3.0.5
  flutter_local_notifications: ^0.8.4+3
  rxdart: ^0.22.6
  vibrate: ^0.0.4
  flutter_earth: ^0.0.4
  device_info: ^0.4.1+4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/bundle1.png
    - assets/images/bundle2.png
    - assets/images/bundle3.png
    - assets/images/background.png
    - assets/images/logo.png
    - assets/city.json

  fonts:
    - family: shouji
      fonts:
        - asset: assets/fonts/FangZhengShouJi.TTF
          weight: 500
    - family: pinshang
      fonts:
        - asset: assets/fonts/FangZhengPinShang.TTF
          weight: 500
    - family: myicons
      fonts:
        - asset: assets/icons/my_icon.ttf
